### ISSUE TITLE
Duplicate skin images for name and uuid?

### ISSUE THREAD

**Issue by AlexDicy** [mattiabasone/minepic#1]
If I can understand correctly you save 2 copies of skin image for player, one by name and one by uuid, is this correct?

**Comment by mattiabasone** [comment]
The skins are saved as "uuid.png", only Steve has the skin saved using username and uuid. The "steve.png" is used only as "404" for accounts without skin.

**Comment by AlexDicy** [comment]
Ok thanks for the clarification
