### ISSUE TITLE
Add second layer to skin

### ISSUE THREAD

**Issue by SteffoSpieler** [mattiabasone/minepic#6]
I found out, that minepic can't show the second layer of a skin.
e.g. 
![grafik](https://user-images.githubusercontent.com/41108856/105247498-2aa9bb80-5b75-11eb-8b12-10eece37cbbd.png)

I actually use another service, which shows the second layer, but sadly this service isn't good anymore. (In this Skin the 2. Layer of the legs are wrong)
![grafik](https://user-images.githubusercontent.com/41108856/105247633-617fd180-5b75-11eb-8d45-41e1195c3037.png)

I hope you can add the second layer, because I would love to use minepic instead of minotar.

**Comment by mattiabasone** [comment]
Thank you for your suggestion, I'll take a look at it :)

**Comment by SteffoSpieler** [comment]
Wow.. You responded. (The Author of minotar doesn't respond to issues..)

**Comment by mattiabasone** [comment]
This is the correct render, right?

![immagine](https://user-images.githubusercontent.com/3951536/105629080-33cead00-5e41-11eb-8444-0f9e4f109715.png)

**Comment by SteffoSpieler** [comment]
Yes, it is the correct render.

**Comment by mattiabasone** [comment]
@SteffoSpieler should be fixed now :) 

https://minepic.org/skin/Alphawolf_Yasu

![immagine](https://user-images.githubusercontent.com/3951536/105769087-93ba7600-5f5d-11eb-9285-dd45119ff5d6.png)

**Comment by SteffoSpieler** [comment]
Yes it is fixed now. Thanks a lot.

If you want, you can close this issue.
